/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utsmta_mstar_MstarNative */

#ifndef _Included_com_utsmta_mstar_MstarNative
#define _Included_com_utsmta_mstar_MstarNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utsmta_mstar_MstarNative
 * Method:    scan_touch_pad_key
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_utsmta_mstar_MstarNative_scan_1touch_1pad_1key
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
