ATTACH_PRODUCT := device/mstar/arbutus

# Default value, if not overridden else where.
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR ?= device/mstar/arbutus/bluetooth

TARGET_NO_BOOTLOADER := true

BOARD_KERNEL_BASE  := 0x20280000
BOARD_DTB_BASE     := 0x23000000
BOARD_BOOTM_BASE   := 0x24D00000
BOARD_TFTP_ADDRESS := 0x20200000

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a53
TARGET_CPU_VARIANT := generic
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_VARIANT := cortex-a7
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi

TARGET_USES_64_BIT_BINDER := true

TARGET_BOARD_PLATFORM := monet
TARGET_BOARD_PLATFORM_CPU := ARM CA53 Dual-core@1GMHz
TARGET_BOARD_PLATFORM_GPU := Mali-T720 2pp@504MHz

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_PROVIDES_INIT_RC := true

USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
BOARD_EGL_CFG := device/mstar/arbutus/egl.cfg
BOARD_EGL_WORKAROUND_BUG_10194508 := true

BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true

TARGET_RECOVERY_PIXEL_FORMAT := "ABGR_8888"
TARGET_RECOVERY_FSTAB := device/mstar/arbutus/fstab.monet

#BOARD_LIB_DUMPSTATE := libdumpstate.monet

# Wifi related defines
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd
BOARD_WLAN_DEVICE           := bcmdhd

# TV architecture: sn/mi/ddi
BUILD_MSTARTV := sn

# Bionic libm
BUILD_WITH_OPTIMIZE_LIBM := true

BUILD_WITH_MSTAR_MM := true

ENABLE_GAMECURSOR := true
ENABLE_HWC14_CURSOR := true

ENABLE_STR := true

# Vold related defines
BOARD_NO_SDCARD := false
BOARD_MMCBLK_AS_SDCARD := 16

# utopia/tvapi path
TARGET_UTOPIA_LIBS_DIR := device/mstar/arbutus/libraries/utopia
TARGET_TVAPI_LIBS_DIR := vendor/mstar/supernova/projects/tvos

# Secure boot and TEE
BUILD_WITH_SECURE_BOOT := true
BUILD_WITH_TEE := true

BUILD_WITH_SUPERNOVA := true

# 0: no mboot; 1: mboot in SPI ; 2: mboot in EMMC ; 3: mboot in EMMC ,SPI(pm)
BOARD_MBOOTIMAGE := 2
BOARD_TEEIMAGE = $(BUILD_WITH_TEE)
BOARD_RTPMIMAGE := true
BOARD_DTBIMAGE := true

# OTA config
OTA_WITH_TIMESTAMP := 0
OTA_WIPECACHE := 0

OTA_WITH_MBOOT = $(BOARD_MBOOTIMAGE)
OTA_RELOAD_ENV := 1
# 0: no tv; 1: tv images ; 2: tv files
OTA_WITH_TV := 1
# 0: no tvconfig; 1: tvconfig.img ; 2: add/delete config files
OTA_WITH_TVCONFIG := 0
OTA_WITH_TEE = $(BOARD_TEEIMAGE)
OTA_WITH_RTPM = $(BOARD_RTPMIMAGE)
OTA_WITH_DTB = $(BOARD_DTBIMAGE)

# SELinux
BOARD_SEPOLICY_DIRS := device/mstar/common/sepolicy
BOARD_SEPOLICY_REPLACE := \
    su.te
BOARD_SEPOLICY_PREFIX_FILES := $(wildcard $(BOARD_SEPOLICY_DIRS)/*)
BOARD_SEPOLICY_FILES := $(BOARD_SEPOLICY_PREFIX_FILES:$(BOARD_SEPOLICY_DIRS)/%=%)
BOARD_SEPOLICY_UNION := $(filter-out $(BOARD_SEPOLICY_REPLACE), $(BOARD_SEPOLICY_FILES))

PRODUCT_BOOT_JARS += scifly.android
PRODUCT_SYSTEM_SERVER_JARS += scifly-service
